apiVersion: v1
kind: Pod
metadata:
  name: dctest
  namespace: sandbox
spec:
  containers:
  - name: dctest
    securityContext:
      privileged: true
    image: dctest:dev
    command: ["/usr/local/bin/pause"]
    volumeMounts:
    - name: scratch
      mountPath: /var/scratch
  volumes:
    - emptyDir: {}
      name: scratch
